# Generated by Django 3.0.2 on 2020-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='shorturl',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
    ]
