# Generated by Django 3.0.2 on 2020-01-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_shorturl_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='shorturl',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
