# Generated by Django 3.0.2 on 2020-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20200126_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='timestap',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
