# Generated by Django 3.0.2 on 2020-01-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_auto_20200126_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
