# Generated by Django 3.0.2 on 2020-01-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0006_auto_20200126_1913'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shorturl',
            managers=[
            ],
        ),
    ]
