# Generated by Django 3.0.2 on 2020-01-29 21:58

from django.db import migrations, models
import shortner.validator


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0007_auto_20200126_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validator.validator_url, shortner.validator.validate_dot_com]),
        ),
    ]
